name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main # o la rama principal que uses

permissions:
  contents: write # necesario para escribir en la rama

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # la versión que uses para Astro

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "litoos11@outlook.com"
          git config --global user.name "litoos11"
          cd dist #directorio de salida
          git init
          git remote add origin https://github.com/${{ github.repository }}
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force "https://${GITHUB_TOKEN}@github.com/${{ github.repository }}.git" master:gh-pages
